"""Firefox theming that stays out of the way of the user's own settings.

Per profile we own exactly these things and nothing else:
  chrome/wof-tribe.css           the browser UI colours (imported from userChrome.css)
  chrome/wof-tribe-content.css   the new tab page (imported from userContent.css)
  one marked line at the top of userChrome.css / userContent.css
  one marked block in user.js
Everything else in those files is preserved, and `remove()` takes it all out again.
"""
import configparser
import re
from pathlib import Path

from . import colors as c
from . import paths, patterns
from .assets import palette

MARK = "Wings of Fire OS"
BEGIN = f"// BEGIN {MARK} (managed by Pyrrhia Settings; edits inside this block are replaced)"
END = f"// END {MARK}"
BLOCK_RE = re.compile(rf"^// BEGIN {re.escape(MARK)}.*?^// END {re.escape(MARK)}\n?", re.M | re.S)
IMPORT_LINE = {"userChrome.css": '@import url("wof-tribe.css"); /* ' + MARK + " */\n",
               "userContent.css": '@import url("wof-tribe-content.css"); /* ' + MARK + " */\n"}
DEFAULT_PROFILE = "wof.default-esr"


def firefox_roots():
    home = paths.home()
    return [home / ".mozilla/firefox", paths.config_home() / "mozilla/firefox"]


def profiles(create=False):
    """Profile directories listed in every profiles.ini. With create=True, make a default
    profile when there is none so the theme is there on Firefox's first start."""
    found = []
    for root in firefox_roots():
        ini = root / "profiles.ini"
        if not ini.is_file():
            continue
        parser = configparser.RawConfigParser()
        parser.optionxform = str
        try:
            parser.read(ini)
        except configparser.Error:
            continue
        for section in parser.sections():
            if not section.startswith("Profile") or "Path" not in parser[section]:
                continue
            entry = parser[section]
            path = Path(entry["Path"])
            if entry.get("IsRelative", "1") == "1":
                path = root / path
            found.append(path)
    if not found and create:
        found.append(_create_default_profile())
    return found


def _create_default_profile():
    root = firefox_roots()[0]
    profile = root / DEFAULT_PROFILE
    profile.mkdir(parents=True, exist_ok=True)
    (root / "profiles.ini").write_text(
        "[Profile0]\nName=default-esr\nIsRelative=1\nPath=" + DEFAULT_PROFILE + "\nDefault=1\n\n"
        "[General]\nStartWithLastProfile=1\nVersion=2\n")
    return profile


def prefs_block(tribe):
    lines = [
        BEGIN,
        'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);',
        f'user_pref("layout.css.prefers-color-scheme.content-override", {0 if tribe.dark else 1});',
        f'user_pref("wingsoffire.tribe", "{tribe.id}");',
        END,
    ]
    return "\n".join(lines) + "\n"


def replace_block(text, block):
    """Put `block` in place of any existing managed block (or at the end), leaving the rest alone."""
    if BLOCK_RE.search(text):
        return BLOCK_RE.sub(lambda _m: block, text, count=1)
    if text and not text.endswith("\n"):
        text += "\n"
    return text + block


def remove_block(text):
    return BLOCK_RE.sub("", text)


def ensure_import(text, filename):
    line = IMPORT_LINE[filename]
    if line in text:
        return text
    # @import has to come before any other rule, so it goes first (after a @charset if any).
    if text.startswith("@charset"):
        first, _, rest = text.partition("\n")
        return first + "\n" + line + rest
    return line + text


def remove_import(text, filename):
    return text.replace(IMPORT_LINE[filename], "")


def chrome_css(tribe):
    p = palette.of(tribe)
    frame = c.mix(p.background, p.accent, 0.1)
    toolbar = p.surface
    field = p.background if p.dark else "#ffffff"
    tile = patterns.data_uri(patterns.svg(tribe.pattern, p.accent, opacity=0.18))
    return f"""/* {tribe.name} theme for Firefox. Generated by Wings of Fire OS - changes will be overwritten.
   To stop Wings of Fire OS theming Firefox, untick Firefox in Pyrrhia Settings. */
:root {{
  --lwt-accent-color: {frame} !important;
  --lwt-text-color: {p.text} !important;
  --lwt-accent-color-inactive: {c.mix(frame, p.background, 0.5)} !important;
  --toolbar-bgcolor: {toolbar} !important;
  --toolbar-color: {p.text} !important;
  --toolbarbutton-icon-fill: {p.text} !important;
  --toolbarbutton-icon-fill-attention: {p.accent} !important;
  --toolbarbutton-hover-background: {c.rgba(p.accent, 0.2)} !important;
  --toolbarbutton-active-background: {c.rgba(p.accent, 0.35)} !important;
  --tab-selected-bgcolor: {toolbar} !important;
  --tab-selected-textcolor: {p.text} !important;
  --tab-loading-fill: {p.accent} !important;
  --toolbar-field-background-color: {field} !important;
  --toolbar-field-color: {p.text} !important;
  --toolbar-field-border-color: {p.border} !important;
  --toolbar-field-focus-background-color: {field} !important;
  --toolbar-field-focus-color: {p.text} !important;
  --toolbar-field-focus-border-color: {p.accent} !important;
  --focus-outline-color: {p.accent} !important;
  --urlbarView-highlight-background: {p.accent} !important;
  --urlbarView-highlight-color: {p.on_accent} !important;
  --urlbar-box-bgcolor: {p.raised} !important;
  --arrowpanel-background: {p.surface} !important;
  --arrowpanel-color: {p.text} !important;
  --arrowpanel-border-color: {p.border} !important;
  --panel-item-hover-bgcolor: {c.rgba(p.accent, 0.2)} !important;
  --sidebar-background-color: {p.sunken} !important;
  --sidebar-text-color: {p.text} !important;
  --tabpanel-background-color: {p.background} !important;
  --button-primary-bgcolor: {p.accent} !important;
  --button-primary-color: {p.on_accent} !important;
  --color-accent-primary: {p.accent} !important;
}}
#navigator-toolbox {{
  background-color: {frame} !important;
  background-image: url("{tile}") !important;
  border-bottom-color: {p.accent} !important;
}}
.tab-background:is([selected], [multiselected]) {{
  box-shadow: inset 0 2px 0 {p.accent}, 0 0 4px rgba(0, 0, 0, 0.3) !important;
}}
#nav-bar, #PersonalToolbar {{ background-color: {toolbar} !important; background-image: none !important; }}
"""


def content_css(tribe):
    p = palette.of(tribe)
    tile = patterns.data_uri(patterns.svg(tribe.pattern, p.accent, opacity=0.15))
    card = p.surface
    return f"""/* {tribe.name} new tab page. Generated by Wings of Fire OS - changes will be overwritten. */
@-moz-document url("about:home"), url("about:newtab"), url("about:privatebrowsing") {{
  body, .activity-stream {{
    --newtab-background-color: {p.background} !important;
    --newtab-background-color-secondary: {card} !important;
    --newtab-text-primary-color: {p.text} !important;
    --newtab-primary-action-background: {p.accent} !important;
    --newtab-element-hover-color: {c.rgba(p.accent, 0.2)} !important;
    background-color: {p.background} !important;
    background-image: url("{tile}") !important;
    color: {p.text} !important;
  }}
}}
"""


def apply(tribe):
    """Theme every profile. Returns the profiles touched."""
    touched = []
    block = prefs_block(tribe)
    for profile in profiles(create=True):
        chrome = profile / "chrome"
        chrome.mkdir(parents=True, exist_ok=True)
        (chrome / "wof-tribe.css").write_text(chrome_css(tribe))
        (chrome / "wof-tribe-content.css").write_text(content_css(tribe))
        for name in IMPORT_LINE:
            path = chrome / name
            old = path.read_text() if path.exists() else ""
            new = ensure_import(old, name)
            if new != old:
                path.write_text(new)
        user_js = profile / "user.js"
        old = user_js.read_text() if user_js.exists() else ""
        new = replace_block(old, block)
        if new != old:
            user_js.write_text(new)
        touched.append(profile)
    return touched


def remove():
    """Undo everything `apply` did, keeping the user's own CSS and prefs."""
    for profile in profiles():
        chrome = profile / "chrome"
        for name in ("wof-tribe.css", "wof-tribe-content.css"):
            (chrome / name).unlink(missing_ok=True)
        for name in IMPORT_LINE:
            path = chrome / name
            if path.exists():
                text = remove_import(path.read_text(), name)
                if text.strip():
                    path.write_text(text)
                else:
                    path.unlink()
        user_js = profile / "user.js"
        if user_js.exists():
            user_js.write_text(remove_block(user_js.read_text()))


def running():
    """True if Firefox is open (theme changes show after it restarts)."""
    for proc in Path("/proc").iterdir():
        if proc.name.isdigit():
            try:
                name = (proc / "comm").read_text().strip()
            except OSError:
                continue
            if name in ("firefox", "firefox-esr", "firefox-bin"):
                return True
    return False
